apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: guacamole-operator-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: image-registry.openshift-image-registry.svc:5000/guacamole-operator-system/guacamole-operator-catalog:0.0.6
  displayName: Guacamole Operator Catalog
  publisher: Raphael Morsch
  updateStrategy:
    registryPoll:
      interval: 10m
