apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: guacamole-operator-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/ramoreir/guacamole-operator-catalog:0.0.22
  displayName: Guacamole Operator Catalog
  publisher: Raphael Morsch
  updateStrategy:
    registryPoll:
      interval: 5m
