apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: guacamole-operator-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: REPLACE_WITH_REGISTRY/guacamole-operator-catalog:0.0.1
  displayName: Guacamole Operator Catalog
  publisher: Raphael Morsch
  updateStrategy:
    registryPoll:
      interval: 10m
