apiVersion: v1
kind: Secret
metadata:
  name: gateway-openid-client
  namespace: rdp
type: Opaque
stringData:
  password: b190d7844050629582f9009ad00c9428
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-portal-client
  namespace: rdp
type: Opaque
stringData:
  client-secret: 31c8be626e54ba80260516bf91caaf35
