# permissions for end users to view guacamoles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: guacamole-operator
    app.kubernetes.io/managed-by: kustomize
  name: guacamole-viewer-role
rules:
- apiGroups:
  - guacamole.guacamole.io
  resources:
  - guacamoles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - guacamole.guacamole.io
  resources:
  - guacamoles/status
  verbs:
  - get
