# permissions for end users to edit guacamoleconnections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: guacamole-operator
    app.kubernetes.io/managed-by: kustomize
  name: guacamoleconnection-editor-role
rules:
- apiGroups:
  - guacamole.guacamole.io
  resources:
  - guacamoleconnections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - guacamole.guacamole.io
  resources:
  - guacamoleconnections/status
  verbs:
  - get
