//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingSpec) DeepCopyInto(out *AutoscalingSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(int32)
		**out = **in
	}
	if in.TargetMemoryUtilizationPercentage != nil {
		in, out := &in.TargetMemoryUtilizationPercentage, &out.TargetMemoryUtilizationPercentage
		*out = new(int32)
		**out = **in
	}
	if in.TargetCPUUtilizationPercentage != nil {
		in, out := &in.TargetCPUUtilizationPercentage, &out.TargetCPUUtilizationPercentage
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingSpec.
func (in *AutoscalingSpec) DeepCopy() *AutoscalingSpec {
	if in == nil {
		return nil
	}
	out := new(AutoscalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionPermissionSpec) DeepCopyInto(out *ConnectionPermissionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionPermissionSpec.
func (in *ConnectionPermissionSpec) DeepCopy() *ConnectionPermissionSpec {
	if in == nil {
		return nil
	}
	out := new(ConnectionPermissionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionProxySpec) DeepCopyInto(out *ConnectionProxySpec) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionProxySpec.
func (in *ConnectionProxySpec) DeepCopy() *ConnectionProxySpec {
	if in == nil {
		return nil
	}
	out := new(ConnectionProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseSpec) DeepCopyInto(out *DatabaseSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSpec.
func (in *DatabaseSpec) DeepCopy() *DatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopDataSourceRef) DeepCopyInto(out *DesktopDataSourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopDataSourceRef.
func (in *DesktopDataSourceRef) DeepCopy() *DesktopDataSourceRef {
	if in == nil {
		return nil
	}
	out := new(DesktopDataSourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopMemberStatus) DeepCopyInto(out *DesktopMemberStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopMemberStatus.
func (in *DesktopMemberStatus) DeepCopy() *DesktopMemberStatus {
	if in == nil {
		return nil
	}
	out := new(DesktopMemberStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopPool) DeepCopyInto(out *DesktopPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopPool.
func (in *DesktopPool) DeepCopy() *DesktopPool {
	if in == nil {
		return nil
	}
	out := new(DesktopPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DesktopPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopPoolGuacamoleSpec) DeepCopyInto(out *DesktopPoolGuacamoleSpec) {
	*out = *in
	out.InstanceRef = in.InstanceRef
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.IgnoreCert != nil {
		in, out := &in.IgnoreCert, &out.IgnoreCert
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopPoolGuacamoleSpec.
func (in *DesktopPoolGuacamoleSpec) DeepCopy() *DesktopPoolGuacamoleSpec {
	if in == nil {
		return nil
	}
	out := new(DesktopPoolGuacamoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopPoolList) DeepCopyInto(out *DesktopPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DesktopPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopPoolList.
func (in *DesktopPoolList) DeepCopy() *DesktopPoolList {
	if in == nil {
		return nil
	}
	out := new(DesktopPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DesktopPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopPoolNetworkSpec) DeepCopyInto(out *DesktopPoolNetworkSpec) {
	*out = *in
	if in.RDPPort != nil {
		in, out := &in.RDPPort, &out.RDPPort
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopPoolNetworkSpec.
func (in *DesktopPoolNetworkSpec) DeepCopy() *DesktopPoolNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(DesktopPoolNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopPoolSourceSpec) DeepCopyInto(out *DesktopPoolSourceSpec) {
	*out = *in
	out.DataSource = in.DataSource
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopPoolSourceSpec.
func (in *DesktopPoolSourceSpec) DeepCopy() *DesktopPoolSourceSpec {
	if in == nil {
		return nil
	}
	out := new(DesktopPoolSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopPoolSpec) DeepCopyInto(out *DesktopPoolSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.MinReady != nil {
		in, out := &in.MinReady, &out.MinReady
		*out = new(int32)
		**out = **in
	}
	if in.BufferSize != nil {
		in, out := &in.BufferSize, &out.BufferSize
		*out = new(int32)
		**out = **in
	}
	if in.MaxSize != nil {
		in, out := &in.MaxSize, &out.MaxSize
		*out = new(int32)
		**out = **in
	}
	out.Source = in.Source
	in.VirtualMachine.DeepCopyInto(&out.VirtualMachine)
	in.Network.DeepCopyInto(&out.Network)
	in.Guacamole.DeepCopyInto(&out.Guacamole)
	if in.CreateConnections != nil {
		in, out := &in.CreateConnections, &out.CreateConnections
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopPoolSpec.
func (in *DesktopPoolSpec) DeepCopy() *DesktopPoolSpec {
	if in == nil {
		return nil
	}
	out := new(DesktopPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopPoolStatus) DeepCopyInto(out *DesktopPoolStatus) {
	*out = *in
	if in.Desktops != nil {
		in, out := &in.Desktops, &out.Desktops
		*out = make([]DesktopMemberStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopPoolStatus.
func (in *DesktopPoolStatus) DeepCopy() *DesktopPoolStatus {
	if in == nil {
		return nil
	}
	out := new(DesktopPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopPoolVMSpec) DeepCopyInto(out *DesktopPoolVMSpec) {
	*out = *in
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopPoolVMSpec.
func (in *DesktopPoolVMSpec) DeepCopy() *DesktopPoolVMSpec {
	if in == nil {
		return nil
	}
	out := new(DesktopPoolVMSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopPortal) DeepCopyInto(out *DesktopPortal) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopPortal.
func (in *DesktopPortal) DeepCopy() *DesktopPortal {
	if in == nil {
		return nil
	}
	out := new(DesktopPortal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DesktopPortal) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopPortalList) DeepCopyInto(out *DesktopPortalList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DesktopPortal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopPortalList.
func (in *DesktopPortalList) DeepCopy() *DesktopPortalList {
	if in == nil {
		return nil
	}
	out := new(DesktopPortalList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DesktopPortalList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopPortalSpec) DeepCopyInto(out *DesktopPortalSpec) {
	*out = *in
	out.DefaultPool = in.DefaultPool
	out.Keycloak = in.Keycloak
	if in.EnablePlugin != nil {
		in, out := &in.EnablePlugin, &out.EnablePlugin
		*out = new(bool)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopPortalSpec.
func (in *DesktopPortalSpec) DeepCopy() *DesktopPortalSpec {
	if in == nil {
		return nil
	}
	out := new(DesktopPortalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopPortalStatus) DeepCopyInto(out *DesktopPortalStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopPortalStatus.
func (in *DesktopPortalStatus) DeepCopy() *DesktopPortalStatus {
	if in == nil {
		return nil
	}
	out := new(DesktopPortalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopSession) DeepCopyInto(out *DesktopSession) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopSession.
func (in *DesktopSession) DeepCopy() *DesktopSession {
	if in == nil {
		return nil
	}
	out := new(DesktopSession)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DesktopSession) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopSessionList) DeepCopyInto(out *DesktopSessionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DesktopSession, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopSessionList.
func (in *DesktopSessionList) DeepCopy() *DesktopSessionList {
	if in == nil {
		return nil
	}
	out := new(DesktopSessionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DesktopSessionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopSessionRequester) DeepCopyInto(out *DesktopSessionRequester) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopSessionRequester.
func (in *DesktopSessionRequester) DeepCopy() *DesktopSessionRequester {
	if in == nil {
		return nil
	}
	out := new(DesktopSessionRequester)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopSessionSpec) DeepCopyInto(out *DesktopSessionSpec) {
	*out = *in
	out.PoolRef = in.PoolRef
	out.Requester = in.Requester
	if in.TTLSecondsAfterReady != nil {
		in, out := &in.TTLSecondsAfterReady, &out.TTLSecondsAfterReady
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopSessionSpec.
func (in *DesktopSessionSpec) DeepCopy() *DesktopSessionSpec {
	if in == nil {
		return nil
	}
	out := new(DesktopSessionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DesktopSessionStatus) DeepCopyInto(out *DesktopSessionStatus) {
	*out = *in
	if in.ReadyAt != nil {
		in, out := &in.ReadyAt, &out.ReadyAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DesktopSessionStatus.
func (in *DesktopSessionStatus) DeepCopy() *DesktopSessionStatus {
	if in == nil {
		return nil
	}
	out := new(DesktopSessionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Guacamole) DeepCopyInto(out *Guacamole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Guacamole.
func (in *Guacamole) DeepCopy() *Guacamole {
	if in == nil {
		return nil
	}
	out := new(Guacamole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Guacamole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuacamoleConnection) DeepCopyInto(out *GuacamoleConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuacamoleConnection.
func (in *GuacamoleConnection) DeepCopy() *GuacamoleConnection {
	if in == nil {
		return nil
	}
	out := new(GuacamoleConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GuacamoleConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuacamoleConnectionList) DeepCopyInto(out *GuacamoleConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GuacamoleConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuacamoleConnectionList.
func (in *GuacamoleConnectionList) DeepCopy() *GuacamoleConnectionList {
	if in == nil {
		return nil
	}
	out := new(GuacamoleConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GuacamoleConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuacamoleConnectionSpec) DeepCopyInto(out *GuacamoleConnectionSpec) {
	*out = *in
	out.GuacamoleRef = in.GuacamoleRef
	if in.MaxConnections != nil {
		in, out := &in.MaxConnections, &out.MaxConnections
		*out = new(int32)
		**out = **in
	}
	if in.MaxConnectionsPerUser != nil {
		in, out := &in.MaxConnectionsPerUser, &out.MaxConnectionsPerUser
		*out = new(int32)
		**out = **in
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(ConnectionProxySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RDP != nil {
		in, out := &in.RDP, &out.RDP
		*out = new(RDPConnectionSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.VNC != nil {
		in, out := &in.VNC, &out.VNC
		*out = new(VNCConnectionSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SSH != nil {
		in, out := &in.SSH, &out.SSH
		*out = new(SSHConnectionSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.AdditionalParameters != nil {
		in, out := &in.AdditionalParameters, &out.AdditionalParameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = make([]ConnectionPermissionSpec, len(*in))
		copy(*out, *in)
	}
	if in.ExposeMetrics != nil {
		in, out := &in.ExposeMetrics, &out.ExposeMetrics
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuacamoleConnectionSpec.
func (in *GuacamoleConnectionSpec) DeepCopy() *GuacamoleConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(GuacamoleConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuacamoleConnectionStatus) DeepCopyInto(out *GuacamoleConnectionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuacamoleConnectionStatus.
func (in *GuacamoleConnectionStatus) DeepCopy() *GuacamoleConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(GuacamoleConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuacamoleInstanceRef) DeepCopyInto(out *GuacamoleInstanceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuacamoleInstanceRef.
func (in *GuacamoleInstanceRef) DeepCopy() *GuacamoleInstanceRef {
	if in == nil {
		return nil
	}
	out := new(GuacamoleInstanceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuacamoleList) DeepCopyInto(out *GuacamoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Guacamole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuacamoleList.
func (in *GuacamoleList) DeepCopy() *GuacamoleList {
	if in == nil {
		return nil
	}
	out := new(GuacamoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GuacamoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuacamoleResources) DeepCopyInto(out *GuacamoleResources) {
	*out = *in
	in.Guacamole.DeepCopyInto(&out.Guacamole)
	in.Guacd.DeepCopyInto(&out.Guacd)
	in.MySQL.DeepCopyInto(&out.MySQL)
	in.MetricsExporter.DeepCopyInto(&out.MetricsExporter)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuacamoleResources.
func (in *GuacamoleResources) DeepCopy() *GuacamoleResources {
	if in == nil {
		return nil
	}
	out := new(GuacamoleResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuacamoleSpec) DeepCopyInto(out *GuacamoleSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.GuacdReplicas != nil {
		in, out := &in.GuacdReplicas, &out.GuacdReplicas
		*out = new(int32)
		**out = **in
	}
	out.Database = in.Database
	in.Route.DeepCopyInto(&out.Route)
	in.Resources.DeepCopyInto(&out.Resources)
	in.Autoscaling.DeepCopyInto(&out.Autoscaling)
	in.GuacdAutoscaling.DeepCopyInto(&out.GuacdAutoscaling)
	in.MetricsExporter.DeepCopyInto(&out.MetricsExporter)
	if in.OpenID != nil {
		in, out := &in.OpenID, &out.OpenID
		*out = new(OpenIDSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuacamoleSpec.
func (in *GuacamoleSpec) DeepCopy() *GuacamoleSpec {
	if in == nil {
		return nil
	}
	out := new(GuacamoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuacamoleStatus) DeepCopyInto(out *GuacamoleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuacamoleStatus.
func (in *GuacamoleStatus) DeepCopy() *GuacamoleStatus {
	if in == nil {
		return nil
	}
	out := new(GuacamoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakUserDirectorySpec) DeepCopyInto(out *KeycloakUserDirectorySpec) {
	*out = *in
	out.ClientSecretRef = in.ClientSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakUserDirectorySpec.
func (in *KeycloakUserDirectorySpec) DeepCopy() *KeycloakUserDirectorySpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakUserDirectorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectReference) DeepCopyInto(out *LocalObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectReference.
func (in *LocalObjectReference) DeepCopy() *LocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(LocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsExporterSpec) DeepCopyInto(out *MetricsExporterSpec) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.ScrapeIntervalSeconds != nil {
		in, out := &in.ScrapeIntervalSeconds, &out.ScrapeIntervalSeconds
		*out = new(int32)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsExporterSpec.
func (in *MetricsExporterSpec) DeepCopy() *MetricsExporterSpec {
	if in == nil {
		return nil
	}
	out := new(MetricsExporterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedObjectReference) DeepCopyInto(out *NamespacedObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedObjectReference.
func (in *NamespacedObjectReference) DeepCopy() *NamespacedObjectReference {
	if in == nil {
		return nil
	}
	out := new(NamespacedObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenIDSpec) DeepCopyInto(out *OpenIDSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ClientSecretRef != nil {
		in, out := &in.ClientSecretRef, &out.ClientSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenIDSpec.
func (in *OpenIDSpec) DeepCopy() *OpenIDSpec {
	if in == nil {
		return nil
	}
	out := new(OpenIDSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RDPConnectionSpec) DeepCopyInto(out *RDPConnectionSpec) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.IgnoreCert != nil {
		in, out := &in.IgnoreCert, &out.IgnoreCert
		*out = new(bool)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(int32)
		**out = **in
	}
	if in.Width != nil {
		in, out := &in.Width, &out.Width
		*out = new(int32)
		**out = **in
	}
	if in.Height != nil {
		in, out := &in.Height, &out.Height
		*out = new(int32)
		**out = **in
	}
	if in.Dpi != nil {
		in, out := &in.Dpi, &out.Dpi
		*out = new(int32)
		**out = **in
	}
	if in.ColorDepth != nil {
		in, out := &in.ColorDepth, &out.ColorDepth
		*out = new(int32)
		**out = **in
	}
	if in.Console != nil {
		in, out := &in.Console, &out.Console
		*out = new(bool)
		**out = **in
	}
	if in.EnableDrive != nil {
		in, out := &in.EnableDrive, &out.EnableDrive
		*out = new(bool)
		**out = **in
	}
	if in.CreateDrivePath != nil {
		in, out := &in.CreateDrivePath, &out.CreateDrivePath
		*out = new(bool)
		**out = **in
	}
	if in.EnablePrinting != nil {
		in, out := &in.EnablePrinting, &out.EnablePrinting
		*out = new(bool)
		**out = **in
	}
	if in.DisableAudio != nil {
		in, out := &in.DisableAudio, &out.DisableAudio
		*out = new(bool)
		**out = **in
	}
	if in.EnableAudioInput != nil {
		in, out := &in.EnableAudioInput, &out.EnableAudioInput
		*out = new(bool)
		**out = **in
	}
	if in.GatewayPort != nil {
		in, out := &in.GatewayPort, &out.GatewayPort
		*out = new(int32)
		**out = **in
	}
	if in.GatewayPasswordSecretRef != nil {
		in, out := &in.GatewayPasswordSecretRef, &out.GatewayPasswordSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.EnableSFTP != nil {
		in, out := &in.EnableSFTP, &out.EnableSFTP
		*out = new(bool)
		**out = **in
	}
	if in.EnableWallpaper != nil {
		in, out := &in.EnableWallpaper, &out.EnableWallpaper
		*out = new(bool)
		**out = **in
	}
	if in.EnableTheming != nil {
		in, out := &in.EnableTheming, &out.EnableTheming
		*out = new(bool)
		**out = **in
	}
	if in.EnableFontSmoothing != nil {
		in, out := &in.EnableFontSmoothing, &out.EnableFontSmoothing
		*out = new(bool)
		**out = **in
	}
	if in.DisableBitmapCaching != nil {
		in, out := &in.DisableBitmapCaching, &out.DisableBitmapCaching
		*out = new(bool)
		**out = **in
	}
	if in.DisableOffscreenCaching != nil {
		in, out := &in.DisableOffscreenCaching, &out.DisableOffscreenCaching
		*out = new(bool)
		**out = **in
	}
	if in.DisableGlyphCaching != nil {
		in, out := &in.DisableGlyphCaching, &out.DisableGlyphCaching
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RDPConnectionSpec.
func (in *RDPConnectionSpec) DeepCopy() *RDPConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(RDPConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteSpec) DeepCopyInto(out *RouteSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteSpec.
func (in *RouteSpec) DeepCopy() *RouteSpec {
	if in == nil {
		return nil
	}
	out := new(RouteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHConnectionSpec) DeepCopyInto(out *SSHConnectionSpec) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.PrivateKeySecretRef != nil {
		in, out := &in.PrivateKeySecretRef, &out.PrivateKeySecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.PassphraseSecretRef != nil {
		in, out := &in.PassphraseSecretRef, &out.PassphraseSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.FontSize != nil {
		in, out := &in.FontSize, &out.FontSize
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHConnectionSpec.
func (in *SSHConnectionSpec) DeepCopy() *SSHConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(SSHConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VNCConnectionSpec) DeepCopyInto(out *VNCConnectionSpec) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(bool)
		**out = **in
	}
	if in.SwapRedBlue != nil {
		in, out := &in.SwapRedBlue, &out.SwapRedBlue
		*out = new(bool)
		**out = **in
	}
	if in.ColorDepth != nil {
		in, out := &in.ColorDepth, &out.ColorDepth
		*out = new(int32)
		**out = **in
	}
	if in.Width != nil {
		in, out := &in.Width, &out.Width
		*out = new(int32)
		**out = **in
	}
	if in.Height != nil {
		in, out := &in.Height, &out.Height
		*out = new(int32)
		**out = **in
	}
	if in.Dpi != nil {
		in, out := &in.Dpi, &out.Dpi
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VNCConnectionSpec.
func (in *VNCConnectionSpec) DeepCopy() *VNCConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(VNCConnectionSpec)
	in.DeepCopyInto(out)
	return out
}
